# Generated by Django 4.1.5 on 2023-01-02 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=250)),
                ('car_img', models.ImageField(upload_to='cars')),
                ('car_ty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cartype')),
            ],
        ),
    ]
